"""Add email and verification status to User model

Revision ID: f63a35f825ae
Revises: 1fd068d87db6
Create Date: 2025-10-03 23:53:15.554763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f63a35f825ae'
down_revision = '1fd068d87db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint("uq_user_email", ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_email", type_='unique')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
